name: "Web log of agrawal-d"
description: "I post random stuff here, mostly related to programming."

url: "https://agrawal-d.github.io" # use this one
baseurl: ""

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-paginate
paginate: 5
paginate_path: /page-:num

#disqus-id: your-disqus-id

source: .
destination: ./_site

sass:
  style: :compressed
  sass_dir: assets/css/
